#!/usr/bin/env python
# compatible with Python 2 or 3
from __future__ import print_function
import json
import sys

def print_dict(D, prefix=''):
    """Print JSON dictionaries as shell exports,
    building nested key path as name."""

    for k, v in D.items():
        if isinstance(v, dict):
            new_prefix = '{}{}_'.format(prefix, k)
            print_dict(v, new_prefix)
        else:
            print('export {}{}="{}"'.format(prefix, k, v))

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("FILE",
                        nargs="?",
                        default="-",
                        help="json file name, omit to pipe from stdin")
    args = parser.parse_args()

    if args.FILE == '-':
        txt = sys.stdin.read()
        print_dict(json.loads(txt))
    else:
        with open(args.FILE) as f:
            print_dict(json.load(f))
