#!/usr/bin/env python
# compatible with Python 2 or 3
from __future__ import print_function
import json

def print_dict(D, prefix=''):
    """Print JSON dictionaries as shell exports,
    building nested key path as name."""

    for k, v in D.items():
        if isinstance(v, dict):
            new_prefix = '{}{}_'.format(prefix + k)
            print_dict(v, new_prefix)
        else:
            print('export {}{}="{}"'.format(prefix, k, v))

if __name__ == "__main__":
    with open("hi.json") as f:
        payload = json.load(f)
        print_dict(payload, '')
